from . import account_tax
from . import ir_attachment
from . import foreign_amount
from . import upload_attach_file
from . import product_note
from . import product_product
from . import product_pricelist_item
from . import product_pricelist
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import sale_order_history
from . import sale_order_line
from . import sale_order_template_line
from . import sale_order_template
