from . import abstract_companion_history_data
from . import abstract_companion_data_sync
from . import companion_sync_log
from . import haverton_activity_question_answer
from . import haverton_address
from . import haverton_code
from . import haverton_defect_category
from . import haverton_location
from . import haverton_region
from . import haverton_service_provider_statutory_requirement
from . import haverton_service_question
from . import haverton_service_type
from . import haverton_work_category
from . import mail_message
from . import project_project
from . import project_project_stage
from . import project_task
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
